pub use super::mail::ActiveModel as MailActive;
pub use super::mail::Entity as MailEntity;
pub use super::mail::Model as MailModel;
pub use super::mail_recipient::ActiveModel as MailRecipientActive;
pub use super::mail_recipient::Entity as MailRecipientEntity;
pub use super::mail_recipient::Model as MailRecipientModel;
pub use super::recipient::ActiveModel as RecipientActive;
pub use super::recipient::Entity as RecipientEntity;
pub use super::recipient::Model as RecipientModel;
